---
languages:
  Python: true

engines:
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          # bump up the mass, as the default
          # was creating some unnecessary noise
          # in duplication reports
          mass_threshold: 40

ratings:
   paths:
   - "**.py"

exclude_paths:
- "dataactcore/migrations/versions"
- "tests/"
