swagger: '2.0'
info:
  title: Check Status API Route
  description: check_status route, updated for sprint 15
  version: '15'
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /check_status:
    post:
      description: |
        A call to this route will provide status information on all jobs associated with the specified submission.
      tags:
        - DB-587
      parameters:
        - name: X-Session-ID
          in: header
          required: true
          type: string
          description: Session identifier
      responses:
        200:
          description: List of validation jobs
          schema:
            type: object
            properties:
              jobs:
                type: array
                items:
                  $ref: '#/definitions/Job'
              cgac_code:
                type: string
              reporting_period_start_date:
                type: string
                description: "MM/YYYY or Q#/YYYY"
              reporting_period_end_date:
                type: string
                description: "MM/YYYY or Q#/YYYY"
              number_of_errors:
                type: number
              number_of_rows:
                type: number
              created_on:
                type: string
                description: "MM/DD/YYYY"
              last_updated:
                type: string
                description: "UTC timestamp YYYY-MM-DD'T'HH:mm:ss"
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
definitions:
  Job:
    type: object
    properties:
      job_id:
        type: number
      job_status:
        type: string
        enum: ["ready", "waiting", "running", "finished", "invalid", "failed"]
        description: |
          "ready" indicates XXXXX
          "waiting" indicates XXXXX, etc.
      job_type:
        type: string
        enum: ["csv_record_validation", "validation"]
        description: |
          "validation" indicates cross-file validation
          "csv_record_validation" indicates single-file-level validation
      filename:
        type: string
      missing_headers:
        type: array
        items:
          type: string
      duplicated_headers:
        type: array
        items:
          type: string
      file_size:
        type: number
        description: Size in bytes
      number_of_rows:
        type: number
      error_type:
        type: string
        enum: ["header_error", "record_level_error"]
      error_data:
        type: array
        items: 
          - $ref: '#/definitions/JobError'
        
  JobError:
    type: object
    properties:
      field_name:
        type: string
      error_name:
        type: string
        enum: ["type_error", "rule_failed"]
      error_description:
        type: string
      occurrences:
        type: number
      rule_failed:
        type: string
        description: "Blank string if not rule_failed"
      rule_label:
        type: string
        description: "Blank if not rule failure, otherwise will be label of rule that failed, e.g. A1 or B11"
      
  Error:
    type: object
    properties:
      message:
        type: string
      errorType:
        type: string
      trace:
        type: string
